name: messenger_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  pinput: ^5.0.0
  firebase_core:
  firebase_auth:
  cloud_firestore:
  google_sign_in:
  intl: ^0.18.1
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.3.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: assets/icon/icon.jpg

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/

  fonts:
    - family: regular
      fonts:
        - asset: assets/fonts/Mulish-Regular.ttf
    - family: bold
      fonts:
        - asset: assets/fonts/Mulish-Bold.ttf
