// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB05sX3XkcEKGE5vT3BPQKBOCcWTh7zNNU',
    appId: '1:308748127974:web:92f9ff3e6abef6bc387527',
    messagingSenderId: '308748127974',
    projectId: 'zynk-65b98',
    authDomain: 'zynk-65b98.firebaseapp.com',
    storageBucket: 'zynk-65b98.firebasestorage.app',
    measurementId: 'G-DMEV9Z2R1Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbRZeXXG2BEwPE15vfe93TmiRGfCNVZ28',
    appId: '1:308748127974:android:0bf32fcb1b9db0cf387527',
    messagingSenderId: '308748127974',
    projectId: 'zynk-65b98',
    storageBucket: 'zynk-65b98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDls0q2SLmANPhTd0zGpGez1eT5o7BluBg',
    appId: '1:308748127974:ios:0481833e926f36a3387527',
    messagingSenderId: '308748127974',
    projectId: 'zynk-65b98',
    storageBucket: 'zynk-65b98.firebasestorage.app',
    iosBundleId: 'com.example.messengerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDls0q2SLmANPhTd0zGpGez1eT5o7BluBg',
    appId: '1:308748127974:ios:0481833e926f36a3387527',
    messagingSenderId: '308748127974',
    projectId: 'zynk-65b98',
    storageBucket: 'zynk-65b98.firebasestorage.app',
    iosBundleId: 'com.example.messengerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB05sX3XkcEKGE5vT3BPQKBOCcWTh7zNNU',
    appId: '1:308748127974:web:67d4bdd4ffc8e5b2387527',
    messagingSenderId: '308748127974',
    projectId: 'zynk-65b98',
    authDomain: 'zynk-65b98.firebaseapp.com',
    storageBucket: 'zynk-65b98.firebasestorage.app',
    measurementId: 'G-KY8NW9W0PF',
  );
}
